export const Actions = {
  POPULATE_ONBOARDING_DATA: "POPULATE_ONBOARDING_DATA",
  UPDATE_ONBOARDING_DATA: "UPDATE_ONBOARDING_DATA",
  RESET_ONBOARDING_DATA: "RESET_ONBOARDING_DATA",
};
export type ActionType = typeof Actions;
